<a href="https://colab.research.google.com/github/swati-bhatt/Practice_MLDA/blob/main/array_vs_list.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Basic Overview

In [ ]:
import numpy as np

In [ ]:
lst=[1,2,3]
print(lst)
print(type(lst))
print("-"*20)

arr=np.array([1,3,2])
print(arr)
print(type(arr))
print("-"*20)

print(arr==lst)
print("-"*20)

print(type(arr.tolist()))
print(arr.tolist()==lst)
print("-"*20)

print(sorted(arr)==sorted(lst))

[1, 2, 3]
<class 'list'>
--------------------
[1 3 2]
<class 'numpy.ndarray'>
--------------------
[ True False False]
--------------------
<class 'list'>
False
--------------------
True


### Adding elements to a array

In [ ]:
lst=[1,2,3]
arr=np.array([1,2,3])

print(lst)
lst.append(4)
print(lst)

print("-"*20)

print(arr)
arr=np.append(arr,4)
print(arr)

[1, 2, 3]
[1, 2, 3, 4]
--------------------
[1 2 3]
[1 2 3 4]


### Removing elements from a array

In [ ]:
lst=[1,2,3]
arr=np.array([1,2,3])

print(lst)
del lst[-2]
print(lst)

print("-"*20)

print(arr)
arr=np.delete(arr,-2)
print(arr)

[1, 2, 3]
[1, 3]
--------------------
[1 2 3]
[1 3]


### Updating an array

In [ ]:
lst=[1,3,2]
arr=np.array([1,3,2])

print(lst)
lst[-2]=2
lst[-1]=3
print(lst)

print("-"*20)

print(arr)
arr[-1]=3
arr[-2]=2
print(arr)

[1, 3, 2]
[1, 2, 3]
--------------------
[1 3 2]
[1 2 3]


## Speed

In [ ]:
import time

my_list=list(range(10000000))
my_arr=np.arange(10000000)

# print(len(my_list))
# print(len(my_arr))

start=time.time()
for i in range(100):
  if 5000000 in my_list:
    pass
end=time.time()
print("Time taken by list  : ",(end-start))

start=time.time()
for i in range(100):
  if 5000000 in my_arr:
    pass
end=time.time()
print("Time taken by array : ",(end-start))

Time taken by list  :  5.90893292427063
Time taken by array :  1.152900218963623


In [ ]:
my_list[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
my_arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])